version: "3.9"

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    image: arthur-springweb:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql-server
      - DB_NAME=my_database
      - DB_USERNAME=admin
      - DB_PASSWORD=admin  
    depends_on:
      - mysql-server
  
  mysql-server:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=my_database
    ports:
      - "3306:3306"