spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver  # Use the appropriate driver for your database
    
  jpa:
    hibernate:
      ddl-auto: update  # This will update the schema automatically based on your entities
    show-sql: true  # Print SQL queries in the console
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8
        #dialect: org.hibernate.dialect.MySQLDialect  # MySQL 5
        dialect: org.hibernate.dialect.MySQL57Dialect  # MySQL 5.7
        # dialect: org.hibernate.dialect.MySQL55Dialect  # MySQL 5.5 

server:
  port: 8080  # HTTP portgit 